/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function homomorphicAdd(ctA: Buffer, ctB: Buffer, serverKey: Buffer): Buffer
export declare function applyAnomalyThreshold(ct: Buffer, serverKey: Buffer, threshold: number): Buffer
export interface TestKeyPair {
  clientKey: Buffer
  serverKey: Buffer
}
export declare function keygenForLocalTesting(): TestKeyPair
export declare function encryptForTesting(value: number, clientKey: Buffer): Buffer
export declare function decryptForTesting(ct: Buffer, clientKey: Buffer): number
export declare function decryptBoolForTesting(ct: Buffer, clientKey: Buffer): boolean
